FROM ubuntu:latest
ENV PATH="/root/.poetry/bin/:/srv/www/.venv/bin:/srv/www/todo_app:${PATH}" 
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential curl
RUN ln /usr/bin/python3 /usr/bin/python
WORKDIR /tmp
#COPY ./requirements.txt .
#RUN pip install -r requirements.txt
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
RUN mkdir /srv/www
WORKDIR /srv/www
COPY ./poetry.toml .
COPY ./pyproject.toml .
COPY ./todo_app ./todo_app
WORKDIR /srv/www/todo_app
RUN poetry config virtualenvs.create false --local && poetry install

RUN adduser nonroot
USER nonroot

ENTRYPOINT ./entrypoint.sh
